import type { ApartmentService } from "./apartmentService";
import type { AuthService } from "./authService";
import type { BalanceService } from "./balanceService";
import type { BillService } from "./billService";
import type { BuildingService } from "./buildingService";
import type { CompoundService } from "./compoundService";
import type { CycleService } from "./cycleService";
import type { PaymentService } from "./paymentService";
import type { UserService } from "./userService";
import { httpApartmentService } from "./http/httpApartmentService";
import { httpAuthService } from "./http/httpAuthService";
import { httpBalanceService } from "./http/httpBalanceService";
import { httpBillService } from "./http/httpBillService";
import { httpBuildingService } from "./http/httpBuildingService";
import { httpCompoundService } from "./http/httpCompoundService";
import { httpCycleService } from "./http/httpCycleService";
import { httpPaymentService } from "./http/httpPaymentService";
import { httpUserService } from "./http/httpUserService";

export const apartmentService: ApartmentService = httpApartmentService;
export const authService: AuthService = httpAuthService;
export const balanceService: BalanceService = httpBalanceService;
export const billService: BillService = httpBillService;
export const buildingService: BuildingService = httpBuildingService;
export const compoundService: CompoundService = httpCompoundService;
export const cycleService: CycleService = httpCycleService;
export const paymentService: PaymentService = httpPaymentService;
export const userService: UserService = httpUserService;

export { AppError, toErrorMessage } from "./appError";
export { setAuthToken, setUnauthorizedHandler } from "./http/httpClient";
