import type { ApartmentService } from "./apartmentService";
import type { AuthService } from "./authService";
import type { BalanceService } from "./balanceService";
import type { BillService } from "./billService";
import type { BuildingService } from "./buildingService";
import type { CompoundService } from "./compoundService";
import type { CycleService } from "./cycleService";
import type { PaymentService } from "./paymentService";
import type { UserService } from "./userService";
import { apiApartmentService } from "./api/apiApartmentService";
import { apiAuthService } from "./api/apiAuthService";
import { apiBalanceService } from "./api/apiBalanceService";
import { apiBillService } from "./api/apiBillService";
import { apiBuildingService } from "./api/apiBuildingService";
import { apiCompoundService } from "./api/apiCompoundService";
import { apiCycleService } from "./api/apiCycleService";
import { apiPaymentService } from "./api/apiPaymentService";
import { apiUserService } from "./api/apiUserService";

export const apartmentService: ApartmentService = apiApartmentService;
export const authService: AuthService = apiAuthService;
export const balanceService: BalanceService = apiBalanceService;
export const billService: BillService = apiBillService;
export const buildingService: BuildingService = apiBuildingService;
export const compoundService: CompoundService = apiCompoundService;
export const cycleService: CycleService = apiCycleService;
export const paymentService: PaymentService = apiPaymentService;
export const userService: UserService = apiUserService;

export { AppError, toErrorMessage } from "./appError";
